package com.android.yetee.yeteemobile.util;

public enum ServiceResultState {
    OK, PASSWORD_NOT_MATCH, NOT_FOUND, CONNECTIVITY_ERROR, SERVICE_INTERNAL_ERROR, UNKNOWN_ERROR,
    CONNECTION_TIMEOUT, LOGIN_ALREADY_EXISTS
}